"""examples.py"""

EX1_RACISM_PAPERSOWL: str = """# Is Racism Still a Current Issue in America?

<!-- from [PapersOwl](https://papersowl.com/) -->

## Introduction

Racism is defined as prejudice, discrimination, or antagonism directed against someone of a different race based on the belief that one’s own race is superior. It is no secret that America has a racist past, with issues like hate crimes, police brutality, and slavery. However, the concern of racism is still apparent in American society today. Completely eliminating racism will be very hard. However, to start the process of eliminating this issue, we need to start by recognizing our own individual prerogatives and use that to learn about other people and their culture.

## Main

There are many people that believe that racism is truly dead. A lot of them believe this because of thenow popular mindset of I don’t see color. Although these are statements/thoughts of ignorance,sometimes, they mean well. Now, in some cases the people saying these things are trying to be allies tocolored people. However, there are people that are only trying to add to the negative protestations andthey don’t really care. They say things like, racism is no longer a thing or existent because there’s onlyone race”the human race. The unfortunate thing is that there are people that really don’t see the problemwith this colorblind philosophy. However, there is definitely an issue with these kinds of assertions. It’salmost like trying to prove you’re not sexist, so you tell a woman that you don’t see gender. Or trying todemonstrate that you’re not homophobic so you say that we all are the same and you don’t notice different sexual orientations. No one benefits from you eliminating certain groups of people for equality.Blinding yourself from someone’s color doesn’t prove any further that you’re an allie, or that you’re notracist, or that you’re woke. It’s just showing that you’re choosing to ignore reality and present prejudicesand that you’re washing away the history and culture of that colored person so that everyone is equal.Except, we aren’t all equal. There’s nothing wrong with acknowledging and celebrating our various racesand our differences as a large society. The problem comes in when people dehumanize others and discriminate against others because of those differences.

64% of Americans believe that racism is still a major problem in our current society, and 30% agree that it still exists however it isn’t a major issue. (nbcnews, 2018) A majority of the people that don’t believe it’s a serious issue are people that have never experienced oppression or any kind of discrimination. According to CNN, 3 out of 4 African Americans currently residing in America believe that they have faced some sort of discrimination and that the country’s criminal justice system favors whites. However, according to NPR, 55% of White Americans feel discriminated against themselves. I conducted a survey and I asked two different groups of 15 people the same question. Is racism still a current issue in America? The first group consisted of only wealthy, Caucasian people. I tried to pick people that haven’t really faced any struggle or discrimination throughout their lives. The second group were only minorities. In the first group, 14 out of the 15 people said yes, racism is still a current issue in America. In the second group 15 out of 15 people said yes. In total, that is 96% of people that still believe that this is an issue, which is still a high amount.

Something else to note is that a lot of people have the mindset that racism only stems from whites beingprejudice towards blacks, when that is not the case. There are many other groups of people that arediscriminated against such as people that identify as Latinx, Native American, Asian American, and anyother people of color. In fact, majorities in many ethnic, and racial groups today in America believe thatdiscrimination exists against their own group, according to a poll from NPR, the Robert Wood JohnsonFoundation and the Harvard T.H. Chan School of Public Health. In Andrew Hacker’s Two Nations, hetalks about the black/white binary paradigm of race. A paradigm is a shared set of understandings orpremises”an accepted model or pattern. The issue with this paradigm is that people that are not whiteOR black’s claims for justice will not be acknowledged. Their claims can be ignored by whites, since they are not black. Their claims can also be ignored by blacks, since they are becoming white. Hacker claimsthat Blackness serves a crucial function in enabling Whiteness to define themselves as privileged andNeed a custom essay on the same topic?superior.

Another reason why a lot of people believe that racism is unfortunately still a large issue in this country is because of everything that has happened in these past couple of years, and all of the things we see in the media. The media plays a huge role in racism in our society. THere have been multiple cases of hate crimes such as lynchings, and shootings that aren’t receiving any news coverage. A larger, more talked about issue is police brutality. Police brutality is the use of excessive and/or unnecessary force by police when dealing with civilians. (S. Danilina, 2015) Although this controversy isn’t anything new, (cases of police brutality have been dated back to the 1800s) this is still a large issue today. The most recurrent form of police brutality is physical. There have been multiple cases of unarmed black individuals losing their lives to to excessive and/or unnecessary force. With 15 black individuals that lost their lives after confrontations with the police, in only six of those cases the officer was fired, and there were only eight cases where the officer was indicted/charged. (Jasmine C. Lee/Haeyoun Park, 2018) Another issue that stems from this is that when police shootings do occur, both trials and convictions are rare, which goes back to African Americans believing that the justice system favors Whites over any other race. Going back to the those 15 cases, out of 15 deaths, 15 police officers that killed unarmed people, only 3 were convicted.

Another occurrence of racial discrimination is redlining. Redlining refers to a discriminatory pattern of disinvestment and obstructive lending practices that act as an impediment to home ownership among African Americans and other people of color. (University of Washington, Seattle, 2017) Red lining was banned around 50 years ago and it still affects minorities in today’s society. The way that it used to work was government surveyors graded neighborhoods, color-coding them. Green was for best, blue was still desirable, yellow was definitely declining and red was hazardous. The redlined areas were the ones that the local lenders discounted as peril, in large part because of the residents’ racial and ethnic demographics. A study done by the National Community Reinvestment Coalition shows that the bulk of neighborhoods and communities marked hazardous in red ink on maps are currently more likely than other areas to comprise lower-income/minority residents.

## Conclusion

In conclusion, racism is still an immense concern. And a lot of society still believes that racism is still a concern. It’s hard to refute the claim of racism when a lot of what we see has to do with racism or discrimination in some way, whether it’s through social media, a real life occurrence, etc. There’s also the fact that the criminal justice system tends to favor whites, there has been an alarming amount of police brutality cases within the last four years, and the fact that redlining still negatively affects many communities of minorities today. Racism will be very hard to completely eliminate. One reason is because some people were born in time periods when it was considered okay to discriminate and be racist towards people that don’t look like them, and a lot of people are stuck in their ways. To start eliminating this, as a country people can start by recognizing their privilege. Racial privilege plays out across multiple environments. Such as social, economic, and cultural. Both checking our privilege and using our privilege to disassemble systemic racism are two ways to begin this convoluted process. People can also do things like call out racist jokes, and try to generate opportunities for people of color that they might not typically have access to. As I previously said, this will be extremely difficult because there’s always going to be people that don’t want to change and accept others. If the majority of society merges together to try to fight this, we will notice a difference in our country.
"""

EX2_VEGANISM_PAPERSOWL: str = """# Is Veganism Beneficial or Detrimental to the Society?

<!-- from [PapersOwl](https://papersowl.com/) -->

Veganism, a “strict vegetarian diet,” is a very popular, yet controversial lifestyle to follow today. According to Alina Petre, a registered dietitian, the online search for the term vegan has risen by more than 250%. The word vegan has become more and more popular amongst society and many have gained more knowledge on the lifestyle itself. When researching the term veganism, according to The Vegan Society the word veganism can be defined as: A philosophy and way of living which seeks to exclude – as far as is possible and practicable – all forms of exploitation of, and cruelty to, animals for food, clothing or any purpose; and by extension, promotes the development and use of animal-free alternatives for the benefit of humans, animals and the environment. In dietary terms it denotes the practice of dispensing with all products derived wholly or partly from animals. Veganism can be thought of as an extreme form of vegetarianism, as vegans ban the all-around consumption or use of any animal product.

Many believe veganism can benefit society in tremendous ways, but many people question if a vegan lifestyle is as beneficial as it is hyped up to be. Majority of those who convert to the strict vegan lifestyle, do so for three popular reasons such as, animal welfare, personal health, and environmental concerns. These three reasonings are often the most controversial to non-vegans. With veganism growing rapidly especially amongst the youth, many people question if the vegan diet is truly beneficial to those following the lifestyle. Veganism is growing very popular in society today, although there are many benefits toveganism there are also many detriments many do not talk about. Vegans follow a very strict diet, asthey stray away from the consumption of all animal products. Many like to think you cannot be pickywhen becoming a vegan, but this is not always the case, in fact the diet of a vegan depends on the typesof foods they prefer to eat. Kathryn Wheeler, an Editorial Assistant at Happiful Magazine, states there arefive different types of vegan diets, such as ethical, plant-based, raw, HCLF, and there are environmentally conscious vegan diets as well.

Although vegans are restricted from the consumption of animal products, they are still able to eat a wide variety of foods. Many of these foods include, fruits, vegetables, whole grains, beans, lentils, nuts, and seeds. Since veganism is an ongoing trend, it is much easier to access. There are many vegan options available at restaurants and grocery stores, as well as vegan restaurants. People who are new to veganism often begin this diet because they want a healthier diet, and for many new vegans they experience changes within their bodies, noticeable from the beginning. Non-vegans are so reliant on processed foods, and this highly affects one’s energy output, whereas “the first thing that someone starting a vegan diet might notice is an energy boost with the removal of the processed meat that is found in many omnivorous diets, in favor of fruit, vegetables, and nuts” (Medlin). A vegan diet will have multiple effects on the body, many vegans argue they are beneficial, although many times deficiencies begin to accumulate after a lack of certain nutrients.

The lifestyle vegans follow can often be described as, “doing no harm” This means you can no longer contribute to factory farming in any shape or form, such as purchasing fur, leather, wool, silk, feathers, and other items where animals are kept out of their natural surroundings and forced to be part of the mass production of goods. It means you “consider all life sacred and choose to harm none” (“The Vegan Lifestyle”). Many vegans describe the lifestyle with the word compassion, and nowadays there are inexpensive alternatives to many things, making the vegan lifestyle more compatible with everyday life. Although this lifestyle is becoming more accessible, many still argue that a vegan lifestyle is still very tedious and can easily become very expensive. The conversion to veganism has increased immensely in recent years, three main reasons why people convert to veganism are animal welfare, personal health, and environmental concerns. Many people are beginning to learn more and more about the cruelNeed a custom essay on the same topic?treatment of animals in factory farming, this has led to many converting to veganism. As they becomemore empathetic towards the animals, they cannot imagine consuming an animal harshly killed forhuman goods. “Preventing the exploitation of animals is not the only reason for becoming vegan, but formany it remains the key factor in their decision to go vegan and stay vegan” (“Why Go Vegan?”).Majority of people who convert to veganism strongly believe animals deserve the right to live in freedom,as humans do. There are also those vegans who switched to the diet for health reasons, “Some research has linked vegan diets with lower blood pressure and cholesterol, and lower rates of heart disease, type 2 diabetes and some types of cancer” (“Why Go Vegan?”).

Some also argue veganism is very beneficial towards the environment, because animal agriculture often causes mass environmental destruction. Vegan blogger, Jasmine Briones argues, “A vegan lifestyle is the best way to reduce your carbon footprint and make a difference daily.” These three reasons are the most common factors in why people convert and remain in the vegan lifestyle. The controversy whether or not veganism is beneficial towards one’s health is an ongoing argument. Those who follow the vegan diet, have experienced many benefits in regard to their health, but there are also many things one can lack from a vegan diet. Many vegans do not talk about the certain nutritional deficiencies they may not be obtaining from their vegan diets. Although the elimination of animal consumption can be beneficial towards one’s weight, cholesterol levels, as well as blood pressure levels, it can also cause many problems with vitamin levels in the body, especially B12, “A vitamin important for the normal formation of red blood cells and the health of the nerve tissues. Undetected and untreated vitamin B12 deficiency can lead to anemia and permanent nerve and brain damage” (“Definition of Vitamin B12”). There are substitute ways to obtain these specific nutrients, those following a vegan diet may be lacking.

Those substitutes could be specific vegan foods, or supplements if they are not getting enough nutrients from the food itself. It is often times very hard for vegans to maintain a healthy, nutrient-based diet, which can be the cause to many deficiencies. This is why vegan nutritionists highly stress “well-planned vegan diets contain all the nutrients we need to remain strong and healthy.” Dietitians Brenda Davis and Vesanto Melina, featured on the Vegan Society explain how sources of calcium can be found amongst multiple food groups. Many vegans struggle with this, because they stick to a fruit and vegetable-based diet, there has to be a mix to receive the right nutrients. The problem is vegans will still pick and choose what foods they want to eat and may lack the nutrients non-vegans receive through the consumption of animal produce. Veganism has become a widespread dietary trend among many nations in the last decade. In the article “The Unstoppable Rise of Veganism,” writer Dan Hancox, shares the thoughts of the newly vegan Louisa Davidson. Louisa is a citizen of the UK and explains the growth of veganism as “We’re riding on that wave of veganism getting into the mainstream” (qtd. in Hancox 1). This shows how fast veganism has grown in the past several years. Vegan diets have been highly encouraged on different social media platforms especially YouTube and Instagram. With very many vegan influencers for people to look to, veganism can be looked at as a “community” and people feel “supported” by those also sharing in the Vegan lifestyle (qtd. in Hancox 1) Social media has left a lasting impression on many, as vegans often share their reasons and how they remain healthy through a vegan diet. This itself has inspired many to quickly convert to veganism.

With veganism gaining more popular day by day, non-vegans ask people who are thinking of convertingto veganism, to really think. Veganism can be a great switch for some people, but it is not for justanyone. According to writer Rachel Hosie, “If the entire population switched to a vegan diet it would havea negative effect on public health.” This is an often-cited argument by those who believe vegan diets are not the best alternative. Many vegans strongly argue that vegandiets save the animals and the environment, yet some non-vegans disagree. When many people become vegan they often times do it for the sole purpose tosave the animals. Many do not even think about thepurpose of benefitting the environment and of course to how veganism can affect a human’s health, especially ina negative aspect. As much as vegans argue they are “saving the world,” they aren’t necessarily doing the environment any good. Some argue that if too many people became vegan, then eventually too many animals would repopulate causing them to need more food, but vegans also eat the same foods as many animals, therefore some animals may starve and die. This may be a far-fetched idea, but it is a valid argument many who are against veganism make. The argument of “ethical omnivorism” and how this supports a “healthy planet” is a very relevant conversation amongst those against veganism. “Ethical omnivorism” strongly supports the idea of local farming and is against “inhumane farming” which is a leading cause of why people convert to veganism. The argument whether or not veganism is all around beneficial is one that many are skeptical of, and although there are many benefits to a vegan diet, there are pros and cons to all diets.

Like all diets veganism can be very beneficial to one’s health but when done incorrectly it can also become very detrimental. Veganism should be a well-planned lifestyle, as many are now taking apart of the “vegan community,” they must learn how to have a balance in the nutrients they need. With veganism becoming more popular, many are accepting vegan’s beliefs, but many are still questioning them. According to Sarah E. Mann, “Controversy regarding the (vegan) diet exists within the public sphere, with those actively supporting and advocating for it, and others questioning its purpose and proposed benefits, even disparaging its existence, perhaps because of a lack of knowledge about the diet.” With the vegan diet continuously growing, there ae more ways to become educated on the diet, and many ways to live out an easier vegan life, since it’s a more accessible subject. Yet the controversy of veganism will most likely always stay at high, because there is still so much research to be done, and many questions to be answered.
"""

EX3_CRITTHINK: str = """# The Importance of Critical Thinking in the Age of Mass Media

<!-- from [custom-writing.org](https://custom-writing.org/) -->

Currently, the importance of critical thinking has grown rapidly because technologicalprogress has led to expanded access to various content-making platforms: websites, onlinenews agencies, and podcasts with, often, low-quality information. Fake news is used toachieve political and financial aims, targeting people with low news literacy. However,individuals can stop spreading fallacies by detecting false agendas with the help of a skepticalattitude.

To begin with, fake information introduced by authors who want to earn money cancause damage to the mental health of emotional people, among whom such news iswidespread. In the post-truth era, which is developing now, people prefer to believe in thestory that appeals to their personal experience rather than the facts (Cooke 212.) For instance,by distributing fabricated stories via the Internet without searching for proof, users helppeople who produce such stories to gain more views that can be monetized later (Cooke 211.)Moreover, such news may be harmful to people's mental health: misinformation may cause aminor panic among them if it concerns, for example, political issues, such as wars and othermilitary conflicts (Burkhardt 6.) Therefore, to prevent mental breakdowns and anxiety, newsconsumers should learn how to detect false agendas and stop their distribution.

Mass media can launch political discussions to achieve ideological purposes that canaffect individuals’ identities. A recently established Computational Propaganda Researchproject has examined political bots in some states and revealed that they play an importantrole in the distribution of information in social networks (Burkhardt 18.) These bots not onlydraw users’ attention to specific political issues but also launch discussions and successfullypersuade people with low critical thinking ability and mold their identity (Burkhardt 18.) Thisexample stands for the fact that misinformation is introduced not merely as a part of amarketing strategy to earn money but as a part of propaganda policy.

Critical thinking is a tool for achieving independence as it helps to recognize by whatmeans mass media misleads public opinion. Scholars emphasize the need for the introductionof critical thinking as a part of education because media literacy increases individuals’autonomy, which is profitable for the democratic states (Atar 72.) However, there appears anissue. After analyzing the quantitative data, Vraga and Tully revealed the relationshipbetween the ability of critical thinking and the level of participation in political discourse.Researchers concluded that the stronger news literacy individual has, the less is theireagerness to discuss and share the latest political content on social media, as they try touncover more reliable sources for making their conclusions (Vraga and Tully 10.) So,skeptical content consumers prevent low-quality content from spreading among other socialmedia users. Therefore, everyone needs to improve critical thinking while consuming thecontent to protect themselves from misinformation.

It can be concluded that because of the free access to social media, there exists lowquality content, including fake news and political bots. People create them with the aim ofmaking money through views and achieving ideological aims by reconstructing users’ onlineidentities. People need to acquire critical thinking skills for protecting themselves from thefalse agenda. This means they need to be skeptical and always strive to figure out what newsand users' profiles are real and what is fabricated. They can do it by checking facts andskipping the emotional component of the story. 
"""
